"""create new field in user model password_updated_at datetime

Revision ID: b7713f2addc3
Revises: 5a49f3532db5
Create Date: 2026-09-27 08:39:24.610983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7713f2addc3'
down_revision: Union[str, None] = '5a49f3532db5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade():
    op.add_column(
        "users",
        sa.Column("password_updated_at", sa.DateTime(timezone=True), nullable=True),
    )

    op.execute("""
        UPDATE users
        SET password_updated_at = COALESCE(created_at, CURRENT_TIMESTAMP)
    """)

    op.alter_column(
        "users",
        "password_updated_at",
        existing_type=sa.DateTime(timezone=True),
        nullable=False,
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_updated_at')
    # ### end Alembic commands ###
