limit_req_zone $binary_remote_addr zone=api_limit:10m rate=20r/s;

server {
    listen 80;
    server_name api.fastapireactboilerplate.com;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name api.fastapireactboilerplate.com;

    ssl_certificate /etc/letsencrypt/live/api.fastapireactboilerplate.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api.fastapireactboilerplate.com/privkey.pem;

    resolver 127.0.0.11 valid=10s ipv6=off;

    location ~ ^/api/(?<api_path>.*)$ {
        limit_req zone=api_limit burst=40 nodelay;

        set $backend_upstream http://backend:8000;
        proxy_pass $backend_upstream/api/$api_path$is_args$args;

        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    gzip on;
    gzip_types text/plain text/css application/javascript application/json image/svg+xml;
    gzip_min_length 256;
}
