name: Deploy frontend to Netlify

on:
  workflow_call:

jobs:
  deploy:
    name: Deploy frontend
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-frontend

      - name: Build
        working-directory: frontend
        run: npm run build

      - name: Deploy to Netlify
        working-directory: frontend
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: npx netlify-cli deploy --prod --dir=dist --no-build
