name: CI frontend

on:
  pull_request:
    branches: [main]

concurrency:
  group: ci-frontend-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            frontend:
              - 'frontend/**'
              - '.github/workflows/_test-frontend.yml'
              - '.github/workflows/ci-frontend.yml'
              - '.github/actions/setup-frontend/**'

  test:
    needs: changes
    if: needs.changes.outputs.frontend == 'true'
    uses: ./.github/workflows/_test-frontend.yml
